### ISSUE TITLE
Sync/Dump all of NPMjs onto IPFS

### ISSUE THREAD

**Issue by awantoch** [valist-io/valist#24]
We need a go program to automatically pull all NPM packages hosted on npmjs.com into an IPFS node

**Comment by nasdf** [comment]
This can be used to pull in changes as they happen.

https://github.com/npm/registry/blob/master/docs/follower.md

**Comment by awantoch** [comment]
We synced 99.98% of NPMjs.com to one of our IPFS nodes, and will make it available on estuary soon!
