### ISSUE TITLE
Launch / Install Options

### ISSUE THREAD

**Issue by nasdf** [valist-io/valist#284]
Launch options enable cross platform releases by specifying which binaries are suitable for each platform.

Potential list of supported platforms and architectures:

* darwin/amd64
* darwin/arm64
* linux/386
* linux/amd64
* linux/arm
* linux/arm64
* windows/386
* windows/amd64

**Comment by nasdf** [comment]
An easy solution could be to use a simple directory structure for example: `darwin/amd64`
This could solve the problems of linking the required files to each specific platform.
A directory labeled `_shared` could include assets used by all releases.

**Comment by awantoch** [comment]
Summary from dev planning convo:

- Bringing back `valist.yml` to map platform architecture to file path
- CLI/GHA/frontend reads this during publish to add info to Release Meta
- CLI/frontend reads this during installation to download correct binary for platform
- Use `~/.valist` folder to map project namespaces and symlink latest version to a folder in $PATH
- support for static, single binaries/simple applications first, then we will explore edge cases like pre-installing dependencies (similar to Steam and Homebrew)

For now we'll support single file binaries in the platform map:

```json
{
    "os/arch": "absolute/path/from/release/dir"
}
```

It will be easy to verify the paths exist during publish as well.
