### ISSUE TITLE
Support for multiple build architectures

### ISSUE THREAD

**Issue by jiyuu-jin** [valist-io/valist#40]
Valist needs a mechanism for building and pinning multiple architecture's artifacts?

Ideally various build artifacts would be pinned with corresponding metadata to a folder and users would then vote on the folder CID versus an individual release CID.

**Comment by jiyuu-jin** [comment]
Potential Publish Flow
------------------------
Example binary project to use a make file to build to multiple architectures.

Artifacts names are in an out array [] in valist.yml

Valist publish, mounts the parent folder of the first artifact.

Files are exported to the out folder

The target artifact files are recursively pinned to a folder based on their path.

A dist.json is constructed where each architecture is the key and each value is the artifact CID.

{
  darwin/amd64: “baf8susiwndodksixnd”,
  linux/amd64: “baf7fjkdjjdgnshbshhuj,
}

The dist.json is published and it’s CID is registered with the publish release function.

**Comment by awantoch** [comment]
Closed by https://github.com/valist-io/registry/pull/3
